credit/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetailClientView.as_view(), name='detail'),
    path('<int:pk>/credit', views.DetailCreditView.as_view(), name='detail_credit'),

    ]

my_website/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('credit/', include('credit.urls')),

]

credit/models.py
from django.db import models


class Client(models.Model):
    name = models.CharField(max_length=20, verbose_name='ФИО Клиента')
    citizenship = models.CharField(max_length=20, verbose_name='Гражданство', default='Кыргызстан')
    birth_year = models.DateField()
    work_place = models.CharField(max_length=30, blank=True)
    update_date = models.DateField(auto_now_add=True)

    class Meta:
        verbose_name = 'Клиент'
        verbose_name_plural = 'Клиенты'
        db_table = 'customers'

    def __str__(self):
        return f'{self.name} - {self.citizenship} - {self.birth_year} - {self.work_place} - {self.update_date}'


class Account(models.Model):
    number = models.CharField(max_length=16, verbose_name='Номер счета', primary_key=True)
    account_type = models.IntegerField(verbose_name='Тип счета', default=1)
    client = models.ForeignKey(Client, verbose_name='Клиент', on_delete=models.CASCADE)

    class Meta:
        verbose_name = 'Счет'
        verbose_name_plural = 'Счета'
        db_table = 'accounts'

    def __str__(self):
        return f'{self.number} - {self.account_type} - {self.client}'


class Credit(models.Model):
    sum = models.IntegerField(verbose_name='Сума')
    date = models.DateField(auto_now_add=True)
    account = models.ForeignKey(Account, verbose_name='счет', on_delete=models.CASCADE)

    class Meta:
        verbose_name = 'Кредит'
        verbose_name_plural = 'Кредиты'
        db_table = 'loans'

    def __str__(self):
        return f'{self.sum} - {self.date} - {self.account}'

credit/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.views import generic

from .models import Client, Account, Credit


class IndexView(generic.ListView):
    template_name = 'index.html'
    context_object_name = 'client_list'

    def get_queryset(self):
        return Client.objects.all()


class DetailClientView(generic.DetailView):
    model = Client
    template_name = 'detail.html'


class DetailCreditView(generic.DetailView):
    model = Account
    template_name = 'detail_credit.html'

credit/templates/detail.html
{% csrf_token %}
<fieldset>
    <legend><h1>{{ client.name }}</h1></legend>
    {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
    {% for account in client.account_set.all %}
       <a href="{% url 'detail_credit' client.id %}">{{ account.number }}</a>
    {% endfor %}
</fieldset>

credit/templates/detail_credit.html
{% csrf_token %}
<fieldset>
    <legend><h1>{{ account.number }}</h1></legend>
    {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
    {% for credit in account.credit_set.all %}
       {{ credit.sum }}
    {% endfor %}
</fieldset>

credit/templates/index.html
{% if client_list %}
    <ul>
    {% for client in client_list %}
        <li><a href="{% url 'detail' client.id %}">{{ client.name }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No clients are available.</p>
{% endif %}